# Generated by Django 2.2.16 on 2020-11-02 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201026_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='timestsmp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
