# Generated by Django 2.2.16 on 2020-11-02 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_timestsmp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='timestsmp',
            new_name='timestamp',
        ),
    ]
