# Generated by Django 2.2.16 on 2020-11-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('orders', '0002_auto_20201124_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Billing_Profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='billing.BillingProfile'),
        ),
        migrations.AddField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
